#!/bin/sh
export SYMFONY__DATABASE__HOST=$MYSQL_PORT_3306_TCP_ADDR
export SYMFONY__DATABASE__PORT=$MYSQL_PORT_3306_TCP_PORT
export SYMFONY__DATABASE__NAME=$MYSQL_1_ENV_MYSQL_DATABASE
export SYMFONY__DATABASE__USER=$MYSQL_1_ENV_MYSQL_USER
export SYMFONY__DATABASE__PASSWORD=$MYSQL_1_ENV_MYSQL_PASSWORD

/bin/sh -c  "composer --ansi $@"